dist: xenial
sudo: true
language: python
python:
  - "3.8"
install:
    - pip install -r requirements.txt
    - npm install
    - pip install sphinx$sphinxconstraint
    - pip install tkinterquickhelper --no-deps
    - export PYTHONPATH=src
script:
  - python setup.py unittests
