[tool.rstcheck]
report_level = "INFO"
ignore_directives = [
    "autosignature",
    "autoclass",
    "autofunction",
    "automodule",
    "blockdiag",
    "image-sg",
    "inheritance-diagram",
    "mathdef",
    "mathdeflist",
    "plot",
    "runpython",
    "quote",
]
ignore_roles = ["epkg", "githublink", "issue"]
ignore_messages = [
    ".*Hyperlink target .* is not referenced.*",
    ".*Document or section may not begin with a transition.*",
    ".*Unknown target name: .*[0-9]{4}.*",
    ".*Duplicate explicit target name: .pdf..*",
    ".*Unexpected possible title overline or transition..*",
]

[tool.ruff]

# Exclude a variety of commonly ignored directories.
exclude = [
    ".eggs",
    ".git",
    "build",
    "dist",
]

# Same as Black.
line-length = 88

[tool.ruff.lint.mccabe]
# Unlike Flake8, default to a complexity level of 10.
max-complexity = 10

[tool.ruff.lint.per-file-ignores]
"_doc/conf.py" = ["F821"]
"lecture_citation/__init__.py" = ["E501"]
"tealecture_citationchpyx/tools/__init__.py" = ["F401"]
