name: Check URLs

on:
  pull_request:
    branches: [main]
  schedule:
    #        ┌───────────── minute (0 - 59)
    #        │  ┌───────────── hour (0 - 23)
    #        │  │ ┌───────────── day of the month (1 - 31)
    #        │  │ │ ┌───────────── month (1 - 12 or JAN-DEC)
    #        │  │ │ │ ┌───────────── day of the week (0 - 6 or SUN-SAT)
    #        │  │ │ │ │
    #        │  │ │ │ │
    #        │  │ │ │ │
    #        *  * * * *
    - cron: '30 1 * * 0'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: urls-checker-code
      uses: urlstechie/urlchecker-action@master
      with:
        subfolder: lecture_citation
        file_types: .md,.py,.rst,.ipynb
        print_all: false
        timeout: 5
        retry_count# : 3
        # exclude_urls: https://dumps.wikimedia.org/other/pageviews/%Y/%Y-%m/pageviews-%Y%m%d-%H0000.gz,https://dumps.wikimedia.org/frwiki/latest/latest-all-titles-in-ns0.gz
        exclude_patterns: https://dumps.wikimedia.org/
        # force_pass : true

    - name: urls-checker-docs
      uses: urlstechie/urlchecker-action@master
      with:
        subfolder: _doc
        file_types: .md,.py,.rst,.ipynb
        print_all: false
        timeout: 5
        retry_count# : 3
        exclude_urls: https://fr.wikipedia.org/wiki/Food_Wars,https://fr.wikipedia.org/wiki/K-ON,https://www.lardennais.fr/id257821/article/2021-05-17/au-lac-de-bairon-la-base-departementale-sera-rasee
        # exclude_patterns: 
        # force_pass : true
